### ISSUE TITLE
Invite page is stuck in loading state for employee view

### ISSUE THREAD

**Issue by mdboop** [project-symi/frontend-symi#65]
First off, very cool project! I was checking it out and found a small bug. I'll open a PR with a fix soon. Hope that's OK!

### Steps to reproduce

1. log into app as employee
2. navigate to "Invites" page
3. page never leaves "loading" state

### Cause

If a user is an employee, they'll hit [this line](https://github.com/project-symi/frontend-symi/blob/master/components/Invites.js#L58), which means that `props.invitations` will never evaluate to `true`, and the loading animation will always be shown. Here's a screenshot of my debugger showing this to be the case:
<img width="588" alt="image" src="https://user-images.githubusercontent.com/8826860/71545218-0a3c1b80-29cc-11ea-93a0-d968925baf13.png">

**Comment by miniengineer** [comment]
Hello!!

Sorry for taking so long to review!!
Thank you for fixing this!!! We were postponing this till the last day and could find enough time to add implementation((

I merged your PR, it seems to work fine, so I will resolve this issue ^^
